// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07FxVQax1tOxhmcHUCXD6veBj7nCTQs0',
    appId: '1:796778173685:web:8ad02456b1d0b5df3761bc',
    messagingSenderId: '796778173685',
    projectId: 'student-note-management',
    authDomain: 'student-note-management.firebaseapp.com',
    storageBucket: 'student-note-management.firebasestorage.app',
    measurementId: 'G-G2EYG4TBCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GlNNsXcf8O9hfYJxKd8nMnrWsjzVfyg',
    appId: '1:796778173685:android:6d208c2e4c44f1393761bc',
    messagingSenderId: '796778173685',
    projectId: 'student-note-management',
    storageBucket: 'student-note-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxQ-LfOrhAYbp9V1RW59WXUEYm4Jr4Fg',
    appId: '1:796778173685:ios:94201c19da4cd3733761bc',
    messagingSenderId: '796778173685',
    projectId: 'student-note-management',
    storageBucket: 'student-note-management.firebasestorage.app',
    iosBundleId: 'com.example.studentNoteManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVxQ-LfOrhAYbp9V1RW59WXUEYm4Jr4Fg',
    appId: '1:796778173685:ios:94201c19da4cd3733761bc',
    messagingSenderId: '796778173685',
    projectId: 'student-note-management',
    storageBucket: 'student-note-management.firebasestorage.app',
    iosBundleId: 'com.example.studentNoteManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD07FxVQax1tOxhmcHUCXD6veBj7nCTQs0',
    appId: '1:796778173685:web:40b532b46fd705983761bc',
    messagingSenderId: '796778173685',
    projectId: 'student-note-management',
    authDomain: 'student-note-management.firebaseapp.com',
    storageBucket: 'student-note-management.firebasestorage.app',
    measurementId: 'G-B71XYQT4H2',
  );
}
